### ISSUE TITLE
Account creation on ACMEv1 is disabled.

### ISSUE THREAD

**Issue by robversluis** [janeczku/rancher-letsencrypt#119] opened 2020-01-10 14:05 UTC
LetsEncrypt client: Failed to register account: acme: Error 403 - urn:acme:error:unauthorized - Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

**Comment by robversluis** [comment] 2020-01-13 08:06
See https://github.com/eggsampler/acme

**Comment by fabinou** [comment] 2020-02-01 21:00
Did you manage to make it work with Rancher ?

**Comment by vkruoso** [comment] 2020-03-04 22:04
Im also looking for a solution to use in Rancher 1. Any ideas?

**Comment by TeslaSolari** [comment] 2020-03-20 18:48
I know what is the issue is but not sure If the owner would patch this.

https://github.com/janeczku/rancher-letsencrypt/blob/09132310fd5bab0b80a7e1d17faca95f441c6a9a/letsencrypt/client.go#L19-L21

It's using the old API endpoint 80% sure if these were updated since it uses Lego that supports v2 it should work :?

**Comment by bkuhl** [comment] 2020-05-02 11:53
For anyone still trying to do this, check out https://gist.github.com/fridgerator/db607d268f1f99329c8f9449e89abb4f

**Comment by digit81** [comment] 2020-10-03 07:22
I have Rancher 1.4
Just had to change image from 
`janeczku/rancher-letsencrypt` 
to 
`vxcontrol/rancher-letsencrypt:v1.0.0`

Certificates are renewed now  :)

Thank you @bkuhl for pointing this instruction.

**Comment by SamMousa** [comment] 2020-11-23 11:08
@robversluis if this issue is solved in v1.0.0, could you close it?

**Closed as completed** 2020-11-23 14:42 UTC
